{{if .Values.postgresqlha.enabled}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{.Values.postgresqlha.secret.postgresql.name}}
type: Opaque
data:
  repmgr-password: {{.Values.postgresqlha.secret.postgresql.repmgrPassword}}
  password: {{.Values.postgresqlha.secret.postgresql.password}}
{{end}}